### ISSUE TITLE
BP_TE_UESample04_SimpleBlendCubeTexture: Cube is all black when loading engine

### ISSUE THREAD

**Issue by jetXS** [TouchDesigner/TouchEngine-UE4-Samples#34]
Unless you fire at one of the arrows, the cube is all black... While it should be displaying the banana.

Probably a small issue with the way the texture is fetched / updated once Engine is loaded, because it cannot be reproduced in TouchDesigner w/ Engine COMP.

**Comment by ddthejj** [comment]
Fixed in 1d4d48301e04cfe591cc89f9dc87cac383b74ab2

**Comment by jetXS** [comment]
Play around shooting at the arrows, there is still visual issues occurring 

![image](https://user-images.githubusercontent.com/10253645/142275203-68cbae20-0673-44c9-9fb2-840a22a03e9b.png)

**Comment by ddthejj** [comment]
Hopefully fixed in a0449631cfba347fb51419d8a2dd0952f54a48c8

**Comment by jetXS** [comment]
On startup, even if the details panel blend value is set at 0.5, it starts with nothing (texture is full black) at the moment, unless one of the arrows is getting triggered / the blend value is changing.

**Comment by jetXS** [comment]
The issue is still occurring on load (make sure your blend value was set to something different than 0 or1, I feel)

![ue04-visualGlitchOnLoad](https://user-images.githubusercontent.com/10253645/144529641-0def7f8e-3982-4d33-8a69-69167f745be2.png)

**Comment by ddthejj** [comment]
Hopefully fixed in f0aba94c9cb5816e0c8e930ac731278ac1e26164

**Comment by jetXS** [comment]
Regression now, it seems it is set to 1.0 by itself on start.

![image](https://user-images.githubusercontent.com/10253645/145282794-54e67410-6ae5-49e8-88de-a651cd4ec962.png)

Just make sure Details panel value is set to 0.5 or something different than 1.0

Hit play, detach from player, check details panel, it should still be set to what you had

Hit On/Off of sample, once loaded, it is set to 1.0

It doesn't have to do with the .tox... the .tox default value is 0.0 anyways.

**Comment by ddthejj** [comment]
fixed in 39e13f7d8c5d770dcce3b3419369b6db39f1d307
